name: electronic_student_journal
description: Electronic student journal application
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7


dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/