name: electronic_student_journal
description: Electronic student journal application
publish_to: 'none' 
version: 0.7.0+1

environment:
  sdk: ^3.0.0

dependencies:
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  excel: ^2.1.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.3.0
  go_router: ^7.0.0
  google_fonts: ^4.0.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  overlay_support: ^2.1.0
  path_provider: ^2.0.15  
  provider: ^6.0.5


dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"