// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV45CKIDZ14IyRPlODmlCm2FyIbx5n7E0',
    appId: '1:340213947966:web:87433d7e3a635ed8d93b6f',
    messagingSenderId: '340213947966',
    projectId: 'electronic-student-journal',
    authDomain: 'electronic-student-journal.firebaseapp.com',
    storageBucket: 'electronic-student-journal.appspot.com',
    measurementId: 'G-89294D3MR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEe1aU_lRiF0Zb8LRtNLtml0bz2LH8uNc',
    appId: '1:340213947966:android:1c7ceea506685203d93b6f',
    messagingSenderId: '340213947966',
    projectId: 'electronic-student-journal',
    storageBucket: 'electronic-student-journal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARFEHkIUWjFWnzKFLQkTVT8NeXxKJwzDU',
    appId: '1:340213947966:ios:4d15301fb46a84ebd93b6f',
    messagingSenderId: '340213947966',
    projectId: 'electronic-student-journal',
    storageBucket: 'electronic-student-journal.appspot.com',
    iosClientId: '340213947966-ho26n86siigpp8r3iglcu4j5j1qnvdap.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicStudentJournalSimple',
  );
}
